/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendRouteImport } from './routes/send'
import { Route as PoolRouteImport } from './routes/pool'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TxHashRouteImport } from './routes/tx.$hash'
import { Route as TokensAddressRouteImport } from './routes/tokens.$address'
import { Route as PoolsAddressRouteImport } from './routes/pools.$address'

const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRoute = PoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxHashRoute = TxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensAddressRoute = TokensAddressRouteImport.update({
  id: '/tokens/$address',
  path: '/tokens/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsAddressRoute = PoolsAddressRouteImport.update({
  id: '/pools/$address',
  path: '/pools/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/pool': typeof PoolRoute
  '/send': typeof SendRoute
  '/pools/$address': typeof PoolsAddressRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/pool': typeof PoolRoute
  '/send': typeof SendRoute
  '/pools/$address': typeof PoolsAddressRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/pool': typeof PoolRoute
  '/send': typeof SendRoute
  '/pools/$address': typeof PoolsAddressRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/pool'
    | '/send'
    | '/pools/$address'
    | '/tokens/$address'
    | '/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/pool'
    | '/send'
    | '/pools/$address'
    | '/tokens/$address'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/pool'
    | '/send'
    | '/pools/$address'
    | '/tokens/$address'
    | '/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  PoolRoute: typeof PoolRoute
  SendRoute: typeof SendRoute
  PoolsAddressRoute: typeof PoolsAddressRoute
  TokensAddressRoute: typeof TokensAddressRoute
  TxHashRoute: typeof TxHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/$hash': {
      id: '/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof TxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$address': {
      id: '/tokens/$address'
      path: '/tokens/$address'
      fullPath: '/tokens/$address'
      preLoaderRoute: typeof TokensAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$address': {
      id: '/pools/$address'
      path: '/pools/$address'
      fullPath: '/pools/$address'
      preLoaderRoute: typeof PoolsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  PoolRoute: PoolRoute,
  SendRoute: SendRoute,
  PoolsAddressRoute: PoolsAddressRoute,
  TokensAddressRoute: TokensAddressRoute,
  TxHashRoute: TxHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
